### ISSUE TITLE
Lucene doesn't work

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#392]
I think since the update to imixs-workflow 4.3.2 lucene doesn't work for me.
First I thought that this was my problem: https://github.com/imixs/imixs-admin/issues/30
But now I updated to 4.3.3-SNAPSHOT and rebuilt the search index which found about 40 documents but the search result is always empty. I deleted the folder of WILDFLY/bin/lucence_index and rebuilt the index again. Nothing helps and there are no logs in the console.

How can I debug this? The log level FINE delivers many logs about the GroupInterceptor but nothing about lucen(c)e...

Was there a update of lucene?

If I am logged in there is a configuration in imixs-admin.

Rebuilding the index delieviers:
```
19:43:49,707 INFO  [org.imixs.workflow.engine.adminp.JobHandlerRebuildIndex] (EJB default - 1) Job REBUILD_LUCENE_INDEX (ae36daeb-44c3-4868-ac30-458c481ee128) - reindexing 36 documents...
19:43:50,099 INFO  [org.imixs.workflow.engine.adminp.JobHandlerRebuildIndex] (EJB default - 1) Job REBUILD_LUCENE_INDEX (ae36daeb-44c3-4868-ac30-458c481ee128) - 36 documents reindexed in 1 sec.  (in total: 36
19:43:50,100 INFO  [org.imixs.workflow.engine.adminp.AdminPService] (EJB default - 1) Job REBUILD_LUCENE_INDEX (ae36daeb-44c3-4868-ac30-458c481ee128) completed - timer stopped
```
The status is: COMPLETED

**Comment by chrisw14** [comment]
Is it possible that it's a problem if the uniqueId of my workitem is not in the form like this?
b7e4b092-3d29-4e81-a755-0eb10270f98d

**Comment by rsoika** [comment]
This sounds strange. There was no change concerning Lucene in the past.
Please activate the logger only for the package: 

`org.imixs.workflow.engine.lucene`

Set the log level to 'finest'. 

This will show you what is going on in Lucen UpdateService and SearchService.
Can you give a example of one of your queries? Maybe I will see why your result is empty. 

Also take a look at your settings in your imixs.properties file concerning the Lucene settings. Especialy the property 'lucence.indexFieldListNoAnalyze' is interesting for structured queries. But only if you are using this optional settings.

**Comment by chrisw14** [comment]
Yes, really strange! Here is a log with lucene:

`21:26:15,883 TRACE [org.jboss.security] (default task-26) PBOX00354: Setting security roles ThreadLocal: {}
21:26:15,883 DEBUG [org.jboss.security] (default task-26) PBOX00293: Exception caught: javax.naming.NameNotFoundException: policyRegistration -- service jboss.naming.context.java.policyRegistration
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:106)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
	at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:235)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.jboss.security.plugins.javaee.EJBAuthorizationHelper.getPolicyRegistrationFromJNDI(EJBAuthorizationHelper.java:353)
	at org.jboss.security.plugins.javaee.EJBAuthorizationHelper.authorize(EJBAuthorizationHelper.java:303)
	at org.jboss.as.security.service.SimpleSecurityManager.authorize(SimpleSecurityManager.java:267)
	at org.jboss.as.ejb3.security.AuthorizationInterceptor.processInvocation(AuthorizationInterceptor.java:132)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:636)
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
	at org.imixs.workflow.engine.DocumentService$$$view22.load(Unknown Source)
	at org.imixs.workflow.engine.lucene.LuceneSearchService.search(LuceneSearchService.java:272)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`

The search query:
`(type: "workitem") AND (application: "workflow")`

**Comment by chrisw14** [comment]
Is there a problem with workitems which do not have the $uniqueId in this form?
b0353fb6-643f-4d46-b436-bef0473e8ab7
Maybe because of the added regex in the @Path?

**Comment by rsoika** [comment]
It looks like something else is not working in your application.The log file does not show any log entries from the LucenSearchService. If you call the search this should generate a log message like:

`
FINEST [org.imixs.workflow.engine.lucene]......lucene search: pageNumber=0 pageSize=30
`

Your jboss.security is logging in trace mode. This generates in deed a lot of messages. Maybe you can switch this logger back to 'INFO' level?
The log message you posed here dose not contain useful information for your current problem.  

I don't think the `@Path` change is related to your problem, neither the format of the $uniqueid. If you call the search method with a query the documentService.load method will not be called. 

Are you able to debug? I fear your code dose not reach the method LuceneSearchService.search(...); maybe for security reasons?

You may also activate the looger for the class 'org.imixs.workflow.engine.DocumentService' with the log level FINEST. This will more information how your search request is processed. 
Take a look [here](https://ralph.blog.imixs.com/2016/04/14/wildfly-logging/) how to setup the logger for wildfly. 

Are you testing the search feature with the imixsadmin client? If so this can still be a JavaScript problem from the admin client. 

If you use the search query 

`
(type: "workitem") AND (application: "workflow")
`

it is necessary that you imixs.properties file contains the following entry:

`
lucence.indexFieldListNoAnalyze=application
`

Have you verified this?

**Comment by chrisw14** [comment]
Thank you! Now i renewed the project in eclipse and it's running again.

**Comment by rsoika** [comment]
A good to hear. I guess there was something going wrong in your wildfly server. Changing the workflow version or other components of an already deployed application often forces you to undeploy the existing app first, restart wildfly, and than deploy the new version. I have this situation also typically during development.
