### ISSUE TITLE
Error while deployed to WildFly 13: "Failed to process business interfaces for EJB class"

### ISSUE THREAD

**Issue by mypsp2008** [imixs/imixs-workflow#405]
While deployed to WildFly 13, there are the following errors:
17:47:20,734 INFO  [org.eclipse.persistence.connection] (ServerService Thread Pool -- 21) /vfs:/D:/wildfly-13.0.0.Final/bin/content/imixs-jsf-example-4.0.11.war/WEB-INF/classes/_org.imixs.workflow.jpa login successful
17:47:21,107 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."imixs-jsf-example-4.0.11.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."imixs-jsf-example-4.0.11.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "imixs-jsf-example-4.0.11.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:150)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class org.imixs.workflow.jaxrs.WorkflowRestService
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:96)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
	... 8 more
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method parseWorkitem declared final in org.imixs.workflow.jaxrs.WorkflowRestService
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.verifyNoInterfaceViewMethodsNotDeclaredFinal(BusinessViewAnnotationProcessor.java:228)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.processViewAnnotations(BusinessViewAnnotationProcessor.java:149)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:94)
	... 9 more

17:47:21,108 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 2) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "imixs-jsf-example-4.0.11.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"imixs-jsf-example-4.0.11.war\".POST_MODULE" => "WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"imixs-jsf-example-4.0.11.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class org.imixs.workflow.jaxrs.WorkflowRestService
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method parseWorkitem declared final in org.imixs.workflow.jaxrs.WorkflowRestService"}}
17:47:21,110 ERROR [org.jboss.as.server] (management-handler-thread - 2) WFLYSRV0021: Deploy of deployment "imixs-jsf-example-4.0.11.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"imixs-jsf-example-4.0.11.war\".POST_MODULE" => "WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"imixs-jsf-example-4.0.11.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class org.imixs.workflow.jaxrs.WorkflowRestService
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method parseWorkitem declared final in org.imixs.workflow.jaxrs.WorkflowRestService"}}

**Comment by mypsp2008** [comment]
检测到中文      英语      






















































































  





















  

  
  
  
 

 
 

 
 








 




我正想试试其它版本，也许可以试试WildFly 10
我正想试试其它版本，也许可以试试WildFly 10 



 






















 














  


I'm trying to try another version. Maybe try WildFly 10!

**Comment by mypsp2008** [comment]
I'm trying to try other versions. Try WildFly 10.

**Comment by mypsp2008** [comment]
I'm trying to try other versions.

**Comment by rsoika** [comment]
I just tested successful version 11.0.0-Final. 
Next I will test version 12 and 13.....

**Comment by rsoika** [comment]
I think with the fixes in the latest snapshot release 4.3.6-SNAPSHOT deployment now should work in Wildfly 12 and Wildfly 13. Can you confirm this? 

This would be a great help, if you can verify this in your environment.

**Comment by mypsp2008** [comment]
Using lastest fix:

 	public static ItemCollection parseWorkitem(InputStream requestBodyStream) {  
     		Vector<String> vMultiValueFieldNames = new Vector<String>();  
     		BufferedReader in = new BufferedReader(new InputStreamReader(requestBodyStream));  
     		String inputLine;  

While deployed to WildFly 13, there are still errors:

08:58:23,255 INFO  [org.eclipse.persistence.connection] (ServerService Thread Pool -- 67) /vfs:/D:/wildfly-13.0.0.Final/bin/content/imixs-jsf-example-4.0.11.war/WEB-INF/classes/_org.imixs.workflow.jpa login successful
08:58:23,770 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.deployment.unit."imixs-jsf-example-4.0.11.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."imixs-jsf-example-4.0.11.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "imixs-jsf-example-4.0.11.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:150)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class org.imixs.workflow.jaxrs.WorkflowRestService
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:96)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
	... 8 more
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method parseWorkitem declared final in org.imixs.workflow.jaxrs.WorkflowRestService
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.verifyNoInterfaceViewMethodsNotDeclaredFinal(BusinessViewAnnotationProcessor.java:228)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.processViewAnnotations(BusinessViewAnnotationProcessor.java:149)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:94)
	... 9 more

08:58:23,798 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "imixs-jsf-example-4.0.11.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"imixs-jsf-example-4.0.11.war\".POST_MODULE" => "WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"imixs-jsf-example-4.0.11.war\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class org.imixs.workflow.jaxrs.WorkflowRestService
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method parseWorkitem declared final in org.imixs.workflow.jaxrs.WorkflowRestService"}}
08:58:23,894 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 39) WFLYSRV0010: Deployed "imixs-jsf-example-4.0.11.war" (runtime-name : "imixs-jsf-example-4.0.11.war")
08:58:23,972 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."imixs-jsf-example-4.0.11.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "imixs-jsf-example-4.0.11.war"

Connected to server
[2018-08-01 08:58:24,531] Artifact imixs-jsf-example:war: Artifact is being deployed, please wait...

**Comment by mypsp2008** [comment]
Ok, it works for WildFly 11. thanks a lot!

**Comment by rsoika** [comment]
I also now tested the JSF-Sample Application successfully with wildfly 13. 
If you checkout the latest release of https://github.com/imixs/imixs-jsf-example you can run the application with wildfly 13 in Docker

```
mvn clean install -Pdocker-build
docker-compose up
```

**Comment by mypsp2008** [comment]
Finally ,it can works with WildFly 13.Great!

**Comment by viniciusferneda** [comment]
What was wrong? And what did you have to do to correct it? I have the same problem and I could not find a solution.

**Comment by rsoika** [comment]
Can you please post the deployment error from your current server log file. The upper discussion is a bit out of date. Which version are you using - Wildfly and Imixs-JSF-Sample App ?

**Comment by viniciusferneda** [comment]
I'm doing the server migration in my application, currently it's used JBoss eap 6.4 and now I'm migrating to WildFly 13.0.0.Final.
When I start the WildFly service in my application, the same error mentioned in the previous comments is happening. I wonder how you solved the problem.
Here is the error that is happening in my application with WildFly 13.0.0.Final:

`08:29:07,593 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."cadastro-web-1.39.0-SNAPSHOT.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."cadastro-web-1.39.0-SNAPSHOT.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "cadastro-web-1.39.0-SNAPSHOT.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:150)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0466: Failed to process business interfaces for EJB class class br.com.qualirede.cadastro.domain.estado.EstadoDAO
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:96)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
	... 8 more
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYEJB0498: Business view method setEntityManager declared final in br.com.qualirede.cadastro.domain.estado.EstadoDAO
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.verifyNoInterfaceViewMethodsNotDeclaredFinal(BusinessViewAnnotationProcessor.java:228)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.processViewAnnotations(BusinessViewAnnotationProcessor.java:149)
	at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:94)
	... 9 more`

Thank you

**Comment by viniciusferneda** [comment]
Had a method that was using final, I made the adjustment you mentioned and it worked.

Thank you very much.
