### ISSUE TITLE
Deploy sample on Payara server failed

### ISSUE THREAD

**Issue by rafajurame** [imixs/imixs-workflow#495]
I'm trying to deploy the sample  in Payara server and get the exception:

javax.ejb.AccessLocalException: Client not authorized for this invocation
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:1976)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy474.find(Unknown Source)
	at org.imixs.workflow.engine.__EJB31_Generated__DocumentService__Intf____Bean__.find(Unknown Source)
	at org.imixs.workflow.engine.scheduler.SchedulerService.startAllSchedulers(SchedulerService.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4836)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor545.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

I follow  the deployment guide for glassfish.

**Comment by rsoika** [comment]
It looks like there is some permission missing in the glassfish-ejb-jar.xml file. 
Please post your file than I will have a look into it. 

There should be something like this:

```
		<ejb>
			<ejb-name>SchedulerService</ejb-name>
			<principal>
				<name>WorkflowManager</name>
			</principal>
		</ejb>
```

**Comment by rafajurame** [comment]
Thanks for your answer. Sorry, but i don't find the file . I follow the instructions for deployment and i build with mvn clean install.

**Comment by rsoika** [comment]
Now I can see the same issue in my test environment.
 
I just started an issue in the https://github.com/imixs/imixs-jsf-example project to provide a docker image for payara.

here you can see my setup so far:
https://github.com/imixs/imixs-jsf-example/tree/master/src/docker/configuration/payara

And you are right, there is an issue with the DocumentService and a missing permission. 

I am hopefully that we can figure out what's going wrong here. We use payara also in production. I guess it is the missing deployment descriptor.......

Please let me know if you have new findings concerning payara.

**Comment by rsoika** [comment]
In fact, the wause was the missing Glassfish Files

 * glassfish-ejb-jar.xml
 * glassfish-web.xml

please take a look into the updated WEB-INF folder from the imixs-jsf-example project and add the tow files into your project:

https://github.com/imixs/imixs-jsf-example/tree/master/src/main/webapp/WEB-INF

These two files simply map the principal 'imixs-workflow-service' to the @runas annotation used in some of the Imixs Services. 

I hope that we can kick these files with Jakarat EE8 and the new security annotations.

**Comment by rsoika** [comment]
Have you solved this issue ? Can we close it now?
