### ISSUE TITLE
No write access using groups

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#673]
Hi,
I'm currently using imixs-workflow-5.1.9 and wondering about the following problem:
I have a workitem with $writeaccess = "WF_Admins"
My user admin has a profile with groups = "WF_Admins"
After the login my console prints out:
`10:51:35,476 WARNING [users.GroupInterceptor] (default task-213) resolved UserGroups for 'admin' = 'WF_Admins' `

My GroupInterceptor looks like this:

```
	@AroundInvoke
	public Object intercept(InvocationContext ctx) throws Exception {

		String sMethod = ctx.getMethod().getName();
		String sUserID = ejbCtx.getCallerPrincipal().getName();
		// we can ignore anonymous here!!
		if (sUserID == null || "anonymous".equals(sUserID) || sUserID.isEmpty()) {
			return ctx.proceed();
		}

		// if we have not yet build a USER_GROUP_LIST lets start...
		if (!ctx.getContextData().containsKey(DocumentService.USER_GROUP_LIST)) {
			logger.fine("GroupInterceptor Method=" + sMethod);
			sUserID = ejbCtx.getCallerPrincipal().getName();
			String[] sGroups = lookupService.findGroups(sUserID);
			if (sGroups != null) {
				ctx.getContextData().put(DocumentService.USER_GROUP_LIST, sGroups);
				String groupListe = "";
				for (String aGroup : sGroups) {
					groupListe += "'" + aGroup + "' ";
				}
				logger.fine("resolved UserGroups for '" + sUserID + "' = " + groupListe);
			} else {
				logger.warning("GroupInterceptor: No groups found!");
			}
		}

		return ctx.proceed();
	}
```

But $isAuthor of the mentioned workitem is always false if I use the group instead of the real username.

So, I think the mapping between user and groups is working but I've no write permission.
Was there any change about the used GroupInterceptor?

Thank you.

PS: I updated to imixs-workflow-5.1.12 and have still the same problem.

**Comment by rsoika** [comment]
Hi, sorry for the late response.

To make it short: interceptors are a beast. We do no longer use them and have replaced them completely with CDI events. I guess I have pointed you in the past into the wrong direction.

Just implement a simple CDI Bean with the following method:

```java
public void onUserGroupEvent(@Observes UserGroupEvent userGroupEvent) {
	sUserID = ejbCtx.getCallerPrincipal().getName();
	String[] sGroups = lookupService.findGroups(sUserID);
	if (sGroups != null) {
            logger.fine("onUserGroupEvent (" + sUserID + ") adding groups: " + sGroups + "....");
	    userGroupEvent.setGroups(Arrays.asList(sGroups));
	} else {
		logger.warning("onUserGroupEvent: No groups found!");
	}
}
```

See also [here](https://www.imixs.org/doc/engine/documentservice.html#Inject_Custom_User_Groups)

**Comment by chrisw14** [comment]
Hi,
okay, didn't noticed that... I tried to implement the CDI Bean with @Inject, isn't this the right way?

```
20:49:56,650 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."imixs-workflow-5.1.12.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."imixs-workflow-5.1.12.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1729)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1557)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000408: Observer method cannot be annotated with @Inject, observer methods are automatically injection points: [EnhancedAnnotatedMethodImpl] @Inject public users.GroupInterceptor.onUserGroupEvent(@Observes UserGroupEvent)
	at users.GroupInterceptor.onUserGroupEvent(GroupInterceptor.java:0)
```

I receive the following error:
```
20:49:56,650 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."imixs-workflow-5.1.12.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."imixs-workflow-5.1.12.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1729)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1557)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000408: Observer method cannot be annotated with @Inject, observer methods are automatically injection points: [EnhancedAnnotatedMethodImpl] @Inject public users.GroupInterceptor.onUserGroupEvent(@Observes UserGroupEvent)
	at users.GroupInterceptor.onUserGroupEvent(GroupInterceptor.java:0)
```
