### ISSUE TITLE
Imixs File Upload

### ISSUE THREAD

**Issue by ekoranda** [imixs/imixs-workflow#674]
Hello Ralph, 
I am currently using IMIXS-workflow version 5.0.0 and have a question about the following problem:

I am using `<i:imixsFileUpload id="file_upload_id" />` in order to upload a file into my workitem, however when a user presses fileUpload and selects a file, a popup that says "The file cannot be added because the maximum file size was exceeded appear" pops up, and the console reads the following error: 
`UT005023: Exception handling request to /biocompace/fileupload/: org.jboss.weld.contexts.NonexistentConversationException: WELD-000321: No conversation found to restore for id 1`

I tried adding the web.xml settings that you suggested from https://www.imixs.org/doc/webtools/fileupload.html, however I am still receiving the same error.

Do you have any other suggestions on how to fix this error?

**Comment by rsoika** [comment]
The exception: 

`UT005023: Exception handling request to /biocompace/fileupload/: org.jboss.weld.contexts.NonexistentConversationException: WELD-000321: No conversation found to restore for id 1`

is more related to an invalid web session. 

Try to start a new browser instance and login in again. 

If you work with the JSF-Example you can also upgrade the imixs-workflow-version to 5.1.4 - this can be an issue too. 

So in your pom.xml change 

    .....
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<org.imixs.workflow.version>5.1.4</org.imixs.workflow.version>
		<custom.webResources>src/main/webapp</custom.webResources>
		<custom.unpackTypes>war</custom.unpackTypes>
	</properties>
    .....

Just in the moment I did a test by myself and the fileupload works. (I hope you are testing with a small file?)

**Comment by rsoika** [comment]
Hi did it work for your?

**Comment by ekoranda** [comment]
Unfortunately no I have not been able to fix this issue because When I try to update the workflow version to 5.1.4 I get the following issue:

14:51:15,156 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."biocompace-request-1.0.0.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."biocompace-request-1.0.0.war".WeldStartService: Failed to start service

Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type UpdateService with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject org.imixs.workflow.engine.adminp.JobHandlerRebuildIndex.updateService
  at org.imixs.workflow.engine.adminp.JobHandlerRebuildIndex.updateService(JobHandlerRebuildIndex.java:0)


Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type SearchService with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.imixs.workflow.engine.DocumentService.indexSearchService
  at org.imixs.workflow.engine.DocumentService.indexSearchService(DocumentService.java:0)


I tried to empty my deployments folder like you suggested here https://github.com/imixs/imixs-workflow/issues/606#issuecomment-557899541, but I am still getting the same error.

**Comment by rsoika** [comment]
Ok, I guess you missed the additional depndency in your pom.xml needed since 5.1 ..

		<dependency>
			<groupId>org.imixs.workflow</groupId>
			<artifactId>imixs-workflow-index-lucene</artifactId>
			<version>${org.imixs.workflow.version}</version>
		</dependency>

**Comment by ekoranda** [comment]
Yes that worked in order to update to the newer version of the workflow. Thank you

**Comment by ekoranda** [comment]
I am still however having the issue where I am still getting the same error when I try to upload a file, even if I'm using a very small file.


Here is the entire error I am getting:
WELD-000321: No conversation found to restore for id 1
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.contexts.AbstractConversationContext.initialize(AbstractConversationContext.java:247)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.module.web.context.http.LazyHttpConversationContextImpl.initialize(LazyHttpConversationContextImpl.java:86)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.module.web.context.http.LazyHttpConversationContextImpl.checkContextInitialized(LazyHttpConversationContextImpl.java:120)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:74)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:114)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:78)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:164)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
	at org.jboss.weld.core@3.1.1.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at deployment.biocompace-request-1.0.0.war//org.imixs.workflow.faces.fileupload.FileUploadController$Proxy$_$$_WeldClientProxy.getWorkitem(Unknown Source)
	at deployment.biocompace-request-1.0.0.war//org.imixs.workflow.faces.fileupload.AjaxFileUploadServlet.doPost(AjaxFileUploadServlet.java:62)
	at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rsoika** [comment]
ok but again the WELD-000321: No conversation found to restore for id 1 means that there is an issue with your view scopes.

The FileUploadController bean is @ConversationScoped and also is the WorkflowController.

I can not analyze it form the data I can see if you are working with additional custom controllers using a request scope or session scope?

**Comment by ekoranda** [comment]
I tested the fileupload from your imixs-jsf-example application and am getting the same the error and so it must be an error from my server.

**Comment by rsoika** [comment]
This is very very strange. I know this error message only in conjunction with a outdated session. This conversion ID named in the error message can sometimes be seen in the browser URL constructed by the JSF Framework. And Ajax is a field which can in some cases lead into a problem with the url extensions. If you google for the error message you will find different discussions about this. But we use this fileupload in so many projects and I never had a user complaining about this kind of problem. 

How is you JSF framework setup? Do you store session information on server side (default) or did you change this to client side?

Do you have a chance to debug this in more detail? In your stack-trace no Imixs classes can be seen so it should in deed be a server problem...

**Comment by ekoranda** [comment]
Hello Ralph, one more question about the fileUpload tag. Is it possible to only have the imixsfileuploadtable visible, so that there is no file upload button and the only thing visible is the data table containing the links for all of the files uploaded to that workitem?

**Comment by rsoika** [comment]
Hi, this should work if you set the CSS class 'imixsFileUpload_control'  with display:none:

```
.imixsFileUpload_control, imixsFileUpload_delete {
  display:none;
}
```

**Comment by ekoranda** [comment]
Thank you! That worked great
