### ISSUE TITLE
Extending rest service?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-workflow#675]
Hi,
can I extend the rest-service of imixs-worklow by a custom functionality?
I thought it would work like this but can't access by /api/custom/xyz

```
@ApplicationPath("/api")
public class RestService extends Application {
	
	@Inject
	DocumentService documentService;
	
	@Inject
	DocumentRestService documentRestService;
	
	@GET
	@Path("/custom/{uniqueid}")
	public Response getDocumentByCustomID(@PathParam("uniqueid") String uniqueid, @QueryParam("items") String items,
			@QueryParam("format") String format) {
		
		ItemCollection document = null;
		
		try {
			document = documentService.load(uniqueid);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
		
		return documentRestService.convertResult(document, items, format);
	}
}
```

Thank you.

**Comment by rsoika** [comment]
yes of course you can extend the api.
Just put you resource definition into a separate stateless session ejb or request cdi bean:

```
@Named
@SessionScoped   // or @RequestScoped
public class SearchController extends ViewController implements Serializable {
@GET
	@Path("/custom/{uniqueid}")
	public Response getDocumentByCustomID(@PathParam("uniqueid") String uniqueid, @QueryParam("items") String items,
			@QueryParam("format") String format) {
          ...
}
```

and let the Application bean empty.

**Comment by chrisw14** [comment]
Okay, and what's the right API path to call the custom method?
http://localhost:8080/workflow/api/custom/310A49BE46BD42BEA1EEBB8F7539B7C3
http://localhost:8080/workflow/api/documents/custom/310A49BE46BD42BEA1EEBB8F7539B7C3
... and so on didn't work...

**Comment by rsoika** [comment]
Take a look into the JSF-Sample.  you have a [Application class](https://github.com/imixs/imixs-jsf-example/blob/master/src/main/java/org/imixs/application/ui/RestServiceAPI.java) defining your rest API root path (relative to your web context).

All Imixs-Workflow rest-api resources will be available under this path

And all of your additional defined rest-apis will be available too under there custom path patthern.

Don't forget the beans.xml file.

**Comment by chrisw14** [comment]
Yes, my api-Path is this one: http://localhost:8080/workflow/api
But I don't have access to the /custom/ extension.
What's about the beans.xml? I've nothing added to this file.

**Comment by rsoika** [comment]
It's fine if the beans.xml is empty. Just want to make sure your CDI activated. 
What you are asking here has nothing to do with Imixs-Workflow. It's just a question about how to expose Jax-rs rest api resources in a web application. 

Here again a simple example for a rest resource in Java EE/Jakarta

```
@Named
@RequestScoped
@Path("/team")
@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
public class HelloServcie implements Serializable {

	private static final long serialVersionUID = 1L;
	private static Logger logger = Logger.getLogger(HelloServcie.class.getSimpleName());

	@GET
	@Path("/hello")
	public XMLDataCollection hello() {
		logger.info("Hello World");
		return new XMLDataCollection();
	}
}
```

Do not mix any kind of problem with this project this leads you only in the wrong direction. Make a simple example first and than add the workflow stuff.

**Comment by chrisw14** [comment]
Okay, rest API works. How can I use HTML as an output format?

Nevertheless, I have again this nasty "duplicate class definition bug"...:
```

21:24:19,080 WARNING [com.sun.xml.bind.v2.runtime.reflect.opt.Injector] (default task-48) duplicate class definition bug occured? Please report this : org/imixs/workflow/xml/XMLItem$JaxbAccessorM_getValue_setValue_[Ljava_lang_Object;: java.lang.ClassFormatError: Illegal class name "org/imixs/workflow/xml/XMLItem$JaxbAccessorM_getValue_setValue_[Ljava_lang_Object;" in class file org/imixs/workflow/xml/XMLItem$JaxbAccessorM_getValue_setValue_[Ljava_lang_Object;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:205)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:85)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:89)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:114)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:369)
	at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:65)
	at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:84)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:96)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:124)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:179)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:515)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:534)
	at com.sun.xml.bind.v2.runtime.ArrayBeanInfoImpl.<init>(ArrayBeanInfoImpl.java:74)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:524)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:324)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1140)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:154)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:306)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:295)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:434)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at org.jboss.resteasy.plugins.providers.jaxb.JAXBContextWrapper.<init>(JAXBContextWrapper.java:113)
	at org.jboss.resteasy.plugins.providers.jaxb.JAXBContextWrapper.<init>(JAXBContextWrapper.java:176)
	at org.jboss.resteasy.plugins.providers.jaxb.XmlJAXBContextFinder.createContextObject(XmlJAXBContextFinder.java:51)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBContextFinder.createContext(AbstractJAXBContextFinder.java:174)
	at org.jboss.resteasy.plugins.providers.jaxb.XmlJAXBContextFinder.findCachedContext(XmlJAXBContextFinder.java:40)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.findJAXBContext(AbstractJAXBProvider.java:83)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.getMarshaller(AbstractJAXBProvider.java:173)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.writeTo(AbstractJAXBProvider.java:149)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:137)
	at org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:61)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
	at org.jboss.resteasy.security.doseta.DigitalSigningInterceptor.aroundWriteTo(DigitalSigningInterceptor.java:147)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:129)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:151)
	at org.jboss.resteasy.core.interception.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:398)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:219)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:95)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:529)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:460)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by rsoika** [comment]
Yes this is normal. XML and JSON representation can be rendered by the corresponding default renderer provided in the jax-rs impl. But for HTML a renderer did not exist per default. This is the reason why for HTML you need to write your own renderer. 

Take a look at the [DocumentCollectionWriter](https://github.com/imixs/imixs-workflow/blob/master/imixs-workflow-jax-rs/src/main/java/org/imixs/workflow/jaxrs/DocumentCollectionWriter.java) class. This class implements a MessageBodyWriter for the  XMLDataCollection. This is the trick.

It maybe a lot of additional work and you do not always need a HTML Output for custom object as XML and JSON should be sufficient in your Rest API. So it's just a diligent extra work.

**Comment by chrisw14** [comment]
Okay, and how can I "use" the additional DocumentCollectionWriter in my extension?
I can't find a usage of this writer in another class.
Thank you!!

**Comment by rsoika** [comment]
yes this is a little bit magic. Via reflection the jax-rs impl detects the fitting message writer class

     ......implements MessageBodyWriter<YOUR-XML-CLASS>

So it will work out of the box.

**Comment by chrisw14** [comment]
Yes, seems to be very magic because I'm already using this:
`public class DocumentCollectionWriter implements MessageBodyWriter<org.imixs.workflow.xml.XMLDataCollection> {`
But the HTML representation is not available for my extension. Should I copy all XML classes from org.imixs.workflow.xml?

**Comment by rsoika** [comment]
What are your plan to do?? You want to overwrite the existing MessageBodyWriter Class form the Imixs-Workflow project?

**Comment by rsoika** [comment]
This may be possible with a beans.xml description. But I am not sure. Maybe it is easier to define a new XML Root class (extending XMLDataCollection) and providing a separate MessageBodyWriter for this class. But I can't see a reason why you should do all this. What is your goal?

**Comment by chrisw14** [comment]
Actually, I only want to have this HTML view for my extended rest api but don't know what's needed for it except the DocumentCollectionWriter.

**Comment by rsoika** [comment]
I don't think this is possible because the messagebodywriter is bound a to XML Root Type. 

Either you extend the XMLDataCollection or your implement HTML Rest API Endpoint by your self.
An example can be seen in the ModelRest Service [here](https://github.com/imixs/imixs-workflow/blob/9d1c42bbc729b6aac241843cdb29891035211286/imixs-workflow-jax-rs/src/main/java/org/imixs/workflow/jaxrs/ModelRestService.java#L101)

**Comment by chrisw14** [comment]
Hmm... isn't it possible to add here one type for html?
https://github.com/imixs/imixs-workflow/blob/master/imixs-workflow-jax-rs/src/main/java/org/imixs/workflow/jaxrs/DocumentRestService.java#L550-L575

**Comment by chrisw14** [comment]
... but it also works like in the ModelRestService :-)
Thank you!!
